"""Cython obfuscation build script (Onda 9 #2).

PREREQUISITES
-------------
You need a C compiler matching your Python build:

    Windows : Microsoft Visual C++ Build Tools 14+ (the "Desktop development
              with C++" workload from the VS Installer is enough). Once
              installed, run from a "x64 Native Tools Command Prompt".
    Linux   : gcc + python3-dev. `sudo apt install build-essential python3-dev`.
    macOS   : `xcode-select --install`.

If you don't have a local compiler, build the obfuscated artefacts in CI
(GitHub Actions has gcc on ubuntu-latest by default). Distribute the
resulting .pyd / .so via PyPI wheels.



Compiles the three license-critical Python files into native extension
modules (.pyd on Windows / .so on Linux). The compiled artifacts ship with
distribution; the original .py sources are removed so a static reverse
engineer reaching for license_manager.py sees binary bytecode.

What gets compiled:
    license_manager.py       → license_manager.{pyd,so}
    license_client.py        → license_client.{pyd,so}
    license_server/app.py    → license_server/app.{pyd,so}

What does NOT get compiled:
    license_server/__init__.py   (kept .py — exports nothing important)
    license_server/db.py         (queries are public schema, no secrets)

Honesty
-------
Cython compilation is NOT cryptographically secure. A determined attacker
with cython-disasm, ghidra, or strings + grep can recover most of the
logic. What it DOES buy you:

  • Casual users opening license_manager.py in a text editor see binary.
  • Pattern-matching scrapers won't find the strings "machine_id" or
    "fingerprint" in seconds.
  • Modifying the compiled .pyd requires recompiling — raises the bar.

Combined with cert pinning (Onda 9 #1) and the license server (Onda 8),
this closes the casual-bypass surface. Determined adversaries still have
a path; for them you need code signing + commercial obfuscator (PyArmor,
or AOT-compiled Rust).

Usage
-----
    python build_obfuscated.py                  # default: in-place build
    python build_obfuscated.py --remove-py      # also delete .py sources
                                                  after successful compile
    python build_obfuscated.py --clean          # remove all .c .pyd .so

The build is OPT-IN: standard `pip install` still ships pure .py.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ORCH_DIR = Path(__file__).resolve().parent

# Critical files — order matters (server depends on db, client/manager standalone)
TARGETS = [
    ORCH_DIR / "license_client.py",
    ORCH_DIR / "license_manager.py",
    ORCH_DIR / "license_server" / "app.py",
]

# Artefact extensions to clean (.c is intermediate, .pyd/.so are final, .pyc is bytecode)
ARTEFACT_EXTS = (".c", ".pyd", ".so", ".html")


def _ensure_setup_py() -> Path:
    """Write a setup.py that Cython-compiles the TARGETS in place."""
    setup_path = ORCH_DIR / "setup_obfuscated.py"
    rel_targets = [str(t.relative_to(ORCH_DIR)).replace("\\", "/") for t in TARGETS]
    content = f'''"""Generated by build_obfuscated.py — do not commit by hand."""

from setuptools import setup
from Cython.Build import cythonize

SOURCES = {rel_targets!r}

setup(
    name="dario_license_obfuscated",
    # Tell setuptools we are NOT publishing a normal sdist with packages —
    # we're compiling extensions in place. This avoids auto-discovery which
    # would otherwise try to package all sibling dirs (upgrades/, memory/, ...).
    packages=[],
    py_modules=[],
    ext_modules=cythonize(
        SOURCES,
        compiler_directives={{
            # Onda 10 #3 — Cython hardening directives.
            #
            # The goal here is NOT to make decompilation impossible (it isn't),
            # but to remove every easy footgun that a casual reverser would
            # grep for first: function docstrings, signature objects, source
            # line annotations, raised-exception messages tied to source.
            "language_level": "3",

            # Strip all .__doc__ attributes — function/class docstrings are
            # the easiest source of human-readable hints in compiled .so/.pyd.
            "embedsignature": False,
            "embedsignature.format": "c",    # if anything sneaks through,
                                              # use the C-style without prose
            "docstrings": False,             # drop Python docstrings entirely

            # No PEP 657 fine-grained line numbers — they leak source structure
            # via tracebacks. Stripped tracebacks point only to function name.
            "linetrace": False,
            "always_allow_keywords": True,   # safer for runtime introspection
            "binding": False,                # smaller surface for reflection

            # Anti-debug surface — disable boundscheck and wraparound checks
            # so the generated C is tighter (less recognisable patterns).
            "boundscheck": False,
            "wraparound": False,

            # Hide raised-exception locals (Cython 3.0+) — avoid leaking
            # internal variable names through KeyError / AttributeError messages.
            "c_string_type": "bytes",
            "c_string_encoding": "default",

            # Make the .c file itself harder to grep (each function gets a
            # mangled symbol name in addition to the public Python one).
            "auto_cpdef": False,
            "infer_types": True,
        }},
        # nthreads omitted: Windows + nested setuptools spawn → BrokenProcessPool.
        # Sequential compile takes ~10s for 3 files; acceptable.
    ),
    zip_safe=False,
)
'''
    setup_path.write_text(content, encoding="utf-8")
    return setup_path


def build(remove_py: bool = False) -> int:
    """Run Cython compile in-place. Returns process exit code."""
    setup_path = _ensure_setup_py()
    cmd = [
        sys.executable,
        str(setup_path),
        "build_ext",
        "--inplace",
    ]
    print(f"[build] running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(ORCH_DIR))
    if result.returncode != 0:
        print(f"[build] FAILED with exit code {result.returncode}", file=sys.stderr)
        return result.returncode

    print("[build] compile OK")
    # Show artefacts
    for target in TARGETS:
        base = target.with_suffix("")
        for ext in (".pyd", ".so"):
            for candidate in base.parent.glob(f"{base.name}*{ext}"):
                size_kb = candidate.stat().st_size / 1024
                print(f"  artefact: {candidate.relative_to(ORCH_DIR)}  ({size_kb:.1f} KB)")

    if remove_py:
        for target in TARGETS:
            try:
                target.unlink()
                print(f"  removed source: {target.relative_to(ORCH_DIR)}")
            except FileNotFoundError:
                pass

    # Tidy: remove the build/ dir + intermediate .c (kept by default for debug)
    build_dir = ORCH_DIR / "build"
    if build_dir.exists():
        shutil.rmtree(build_dir, ignore_errors=True)
        print("  removed build/ scratch dir")

    return 0


def clean() -> int:
    """Remove all Cython artefacts so source-only re-runs are reproducible."""
    removed = 0
    for target in TARGETS:
        base = target.with_suffix("")
        for ext in ARTEFACT_EXTS:
            for candidate in base.parent.glob(f"{base.name}*{ext}"):
                # Don't accidentally remove the source .py via globbed name match
                if candidate.suffix in ARTEFACT_EXTS:
                    candidate.unlink()
                    removed += 1
                    print(f"  removed: {candidate.relative_to(ORCH_DIR)}")
    # build/ + setup_obfuscated.py
    for path in (ORCH_DIR / "build", ORCH_DIR / "setup_obfuscated.py"):
        if path.exists():
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()
            removed += 1
            print(f"  removed: {path.relative_to(ORCH_DIR)}")
    print(f"[clean] removed {removed} artefact(s)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Cython obfuscation build (Onda 9 #2)"
    )
    parser.add_argument(
        "--remove-py",
        action="store_true",
        help="After successful compile, delete the original .py sources "
             "(use for distribution builds — DO NOT use during development).",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove all build artefacts (.c, .pyd, .so, build/, setup_obfuscated.py).",
    )
    args = parser.parse_args()

    if args.clean:
        return clean()
    return build(remove_py=args.remove_py)


if __name__ == "__main__":
    sys.exit(main())
