#!/usr/bin/env bash
# DARIO Weekly Backup — automated artifact rollup.
#
# Creates ~/.claude-backups/YYYY-MM-DD-<tag>/ with:
#   - dario-orchestrator.bundle (full git history of ~/.claude)
#   - dario-orchestrator-installer.bundle (if repo exists)
#   - memory.tar.gz (user auto-memory)
#   - orchestrator-runtime.tar.gz (budgets, audit, quality, dream, secrets)
#   - README.md (restore instructions)
#
# Idempotent: re-running on the same day overwrites that day's backup.
# Rotation: keeps the 8 most recent backups (one per week, ~2 months).
#
# Install as cron (Linux):
#   0 3 * * 0 ~/.claude/orchestrator/scripts/backup_weekly.sh
# Install as Windows Task Scheduler:
#   See backup_install_cron.ps1
#
# Exit 0 on success, non-zero on any artifact failure.

set -euo pipefail

CLAUDE_DIR="$HOME/.claude"
BACKUPS_DIR="$HOME/.claude-backups"
INSTALLER_DIR="$HOME/dario-orchestrator-installer"
KEEP_N=8

DATE=$(date +%Y-%m-%d)

# Try to read the current git tag from the orchestrator repo
TAG=$(git -C "$CLAUDE_DIR" describe --tags --abbrev=0 2>/dev/null | sed 's|release/||; s|/|-|g; s|[^A-Za-z0-9._-]|_|g' || echo "untagged")
TARGET="$BACKUPS_DIR/$DATE-$TAG"

echo "═══════════════════════════════════════════════════════"
echo " DARIO Weekly Backup"
echo " Target: $TARGET"
echo "═══════════════════════════════════════════════════════"

mkdir -p "$TARGET"

# 1. Orchestrator repo bundle
if [ -d "$CLAUDE_DIR/.git" ]; then
    echo "[1/4] Bundling dario-orchestrator..."
    git -C "$CLAUDE_DIR" bundle create "$TARGET/dario-orchestrator.bundle" --all
else
    echo "[1/4] SKIP — no git repo at $CLAUDE_DIR/.git"
fi

# 2. Installer repo bundle
if [ -d "$INSTALLER_DIR/.git" ]; then
    echo "[2/4] Bundling dario-orchestrator-installer..."
    git -C "$INSTALLER_DIR" bundle create "$TARGET/dario-orchestrator-installer.bundle" --all
else
    echo "[2/4] SKIP — installer repo not found at $INSTALLER_DIR"
fi

# 3. User memory tarball
MEMORY_DIR="$HOME/.claude/projects/C--Users-barda/memory"
if [ -d "$MEMORY_DIR" ]; then
    echo "[3/4] Bundling user memory..."
    tar -czf "$TARGET/memory.tar.gz" -C "$HOME/.claude/projects/C--Users-barda" memory/
else
    echo "[3/4] SKIP — memory dir not found at $MEMORY_DIR"
fi

# 4. Orchestrator runtime state
cd "$CLAUDE_DIR/orchestrator"
RUNTIME_PATHS=()
for p in budgets audit tasks quality memory dream prometheus company.yaml dario.db .master_secret .license; do
    [ -e "$p" ] && RUNTIME_PATHS+=("$p")
done
if [ ${#RUNTIME_PATHS[@]} -gt 0 ]; then
    echo "[4/4] Bundling orchestrator runtime (${#RUNTIME_PATHS[@]} paths)..."
    tar --exclude='.venv' --exclude='__pycache__' --exclude='*.pyc' \
        -czf "$TARGET/orchestrator-runtime.tar.gz" "${RUNTIME_PATHS[@]}"
else
    echo "[4/4] SKIP — no runtime artifacts found"
fi

# README
HEAD=$(git -C "$CLAUDE_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
cat > "$TARGET/README.md" <<EOF
# DARIO Backup — $DATE — $TAG

**Created:** $(date -Iseconds)
**Tag at HEAD:** \`$TAG\`
**Commit:** \`$HEAD\`
**Auto-generated by:** \`scripts/backup_weekly.sh\`

## Contents

\`\`\`
$(ls -lh "$TARGET" | awk '{print $9, $5}' | grep -v '^$\|^README')
\`\`\`

## Restore

See \`~/.claude-backups/2026-05-25-release_v12.4.0-open-everything/README.md\` for full restore instructions.
EOF

echo ""
echo "Backup contents:"
ls -lh "$TARGET"

# Rotation — keep KEEP_N most recent
cd "$BACKUPS_DIR"
COUNT=$(ls -1d 20*/ 2>/dev/null | wc -l)
if [ "$COUNT" -gt "$KEEP_N" ]; then
    REMOVE=$((COUNT - KEEP_N))
    echo ""
    echo "Rotation: removing $REMOVE old backups (keeping $KEEP_N most recent)..."
    ls -1dt 20*/ | tail -n +$((KEEP_N + 1)) | xargs rm -rf
fi

echo ""
echo "✅ Backup complete: $TARGET"
